In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Zomato Restaurant Dataset.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Rows: 9551
Columns: 21

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   str
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   str
 4   Address               9551 non-null   str
 5   Locality              9551 non-null   str
 6   Locality Verbose      9551 non-null   str
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   str
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   str
 12  Has Table booking     9551 non-null   str
 13  Has Online delivery   9551 non-null   str
 14  Is delivering now     9551 non-null   str
 15  Switch to order menu  9551 non-null   str
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   str
 19  Rating text           9551 non-null   str
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), str(13)
memory usage: 1.5 MB

In [9]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Restaurant ID,9551.0,NaN,NaN,NaN,9051128.349178,8791521.282104,53.0,301962.5,6004089.0,18352291.5,18500652.0
Restaurant Name,9551,7446,Cafe Coffee Day,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country Code,9551.0,NaN,NaN,NaN,18.365616,56.750546,1.0,1.0,1.0,1.0,216.0
City,9551,141,New Delhi,5473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Address,9551,8918,"Dilli Haat, INA, New Delhi",11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Locality,9551,1208,Connaught Place,122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Locality Verbose,9551,1265,"Connaught Place, New Delhi",122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Longitude,9551.0,NaN,NaN,NaN,64.126574,41.467058,-157.948486,77.081343,77.191964,77.282006,174.832089
Latitude,9551.0,NaN,NaN,NaN,25.854381,11.007935,-41.330428,28.478713,28.570469,28.642758,55.97698
Cuisines,9542,1825,North Indian,936,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Average Cost for two,9551.0,NaN,NaN,NaN,1199.210763,16121.183073,0.0,250.0,400.0,700.0,800000.0
Currency,9551,12,Indian Rupees(Rs.),8652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Has Table booking,9551,2,No,8393,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Has Online delivery,9551,2,No,7100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Is delivering now,9551,2,No,9517,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Switch to order menu,9551,1,No,9551,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Price range,9551.0,NaN,NaN,NaN,1.804837,0.905609,1.0,1.0,2.0,2.0,4.0
Aggregate rating,9551.0,NaN,NaN,NaN,2.66637,1.516378,0.0,2.5,3.2,3.7,4.9
Rating color,9551,6,Orange,3737,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rating text,9551,6,Average,3737,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Votes,9551.0,NaN,NaN,NaN,156.909748,430.169145,0.0,5.0,31.0,131.0,10934.0

In [10]:
df.nunique().sort_values()

Switch to order menu       1
Has Online delivery        2
Is delivering now          2
Has Table booking          2
Price range                4
Rating color               6
Rating text                6
Currency                  12
Country Code              15
Aggregate rating          33
Average Cost for two     140
City                     141
Votes                   1012
Locality                1208
Locality Verbose        1265
Cuisines                1825
Restaurant Name         7446
Longitude               8120
Latitude                8677
Address                 8918
Restaurant ID           9551
dtype: int64

In [11]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [12]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

Cuisines    9
dtype: int64

In [14]:
df[df["Cuisines"].isnull()]

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
84,17284105,Cookie Shoppe,216,Albany,"115 N Jackson St, Albany, GA 31701",Albany,"Albany, Albany",-84.154000,31.577200,NaN,...,Dollar($),No,No,No,No,1,3.4,Orange,Average,34
87,17284211,Pearly's Famous Country Cookng,216,Albany,"814 N Slappey Blvd, Albany, GA 31701",Albany,"Albany, Albany",-84.175900,31.588200,NaN,...,Dollar($),No,No,No,No,1,3.4,Orange,Average,36
94,17284158,Jimmie's Hot Dogs,216,Albany,"204 S Jackson St, Albany, GA 31701",Albany,"Albany, Albany",-84.153400,31.575100,NaN,...,Dollar($),No,No,No,No,1,3.9,Yellow,Good,160
297,17374552,Corkscrew Cafe,216,Gainesville,"51 W Main St, Dahlonega, GA 30533",Dahlonega,"Dahlonega, Gainesville",-83.985800,34.531800,NaN,...,Dollar($),No,No,No,No,3,3.9,Yellow,Good,209
328,17501439,Dovetail,216,Macon,"543 Cherry St, Macon, GA 31201",Macon,"Macon, Macon",-83.627979,32.836410,NaN,...,Dollar($),No,No,No,No,3,3.8,Yellow,Good,102
346,17606621,HI Lite Bar & Lounge,216,Miller,"109 N Broadway Ave, Miller, SD 57362",Miller,"Miller, Miller",-98.989100,44.515800,NaN,...,Dollar($),No,No,No,No,1,3.4,Orange,Average,11
368,17059060,Hillstone,216,Orlando,"215 South Orlando Avenue, Winter Park, FL 32789",Winter Park,"Winter Park, Orlando",-81.365260,28.596682,NaN,...,Dollar($),No,No,No,No,3,4.4,Green,Very Good,1158
418,17142698,Leonard's Bakery,216,Rest of Hawaii,"933 Kapahulu Ave, Honolulu, HI 96816",Kaimuki,"Kaimuki, Rest of Hawaii",-157.813432,21.284586,NaN,...,Dollar($),No,No,No,No,1,4.7,Dark Green,Excellent,707
455,17616465,Tybee Island Social Club,216,Savannah,"1311 Butler Ave, Tybee Island, GA 31328",Tybee Island,"Tybee Island, Savannah",-80.848297,31.995810,NaN,...,Dollar($),No,No,No,No,1,3.9,Yellow,Good,309

In [15]:
df["Cuisines"] = df["Cuisines"].fillna("Unknown")

In [17]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                0
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df["Restaurant ID"].duplicated().sum()

np.int64(0)

In [20]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='str')

In [22]:
df.columns=(df.columns.str.strip().str.lower().str.replace(" ","_"))

In [23]:
df.columns

Index(['restaurant_id', 'restaurant_name', 'country_code', 'city', 'address',
       'locality', 'locality_verbose', 'longitude', 'latitude', 'cuisines',
       'average_cost_for_two', 'currency', 'has_table_booking',
       'has_online_delivery', 'is_delivering_now', 'switch_to_order_menu',
       'price_range', 'aggregate_rating', 'rating_color', 'rating_text',
       'votes'],
      dtype='str')

In [24]:
text_cols = [
    "restaurant_name",
    "city",
    "address",
    "locality",
    "locality_verbose",
    "cuisines",
    "currency",
    "rating_color",
    "rating_text"
]

for col in text_cols:
    df[col] = df[col].astype("string").str.strip()

In [44]:
print(df["city"].unique().tolist())

['Makati City', 'Mandaluyong City', 'Pasay City', 'Pasig City', 'Quezon City', 'San Juan City', 'Santa Rosa', 'Tagaytay City', 'Taguig City', 'Brasília', 'Rio de Janeiro', 'S��o Paulo', 'Albany', 'Armidale', 'Athens', 'Augusta', 'Balingup', 'Beechworth', 'Boise', 'Cedar Rapids/Iowa City', 'Chatham-Kent', 'Clatskanie', 'Cochrane', 'Columbus', 'Consort', 'Dalton', 'Davenport', 'Des Moines', 'Dicky Beach', 'Dubuque', 'East Ballina', 'Fernley', 'Flaxton', 'Forrest', 'Gainesville', 'Hepburn Springs', 'Huskisson', 'Inverloch', 'Lakes Entrance', 'Lakeview', 'Lincoln', 'Lorn', 'Macedon', 'Macon', 'Mayfield', 'Mc Millan', 'Middleton Beach', 'Miller', 'Monroe', 'Montville', 'Ojo Caliente', 'Orlando', 'Palm Cove', 'Paynesville', 'Penola', 'Pensacola', 'Phillip Island', 'Pocatello', 'Potrero', 'Princeton', 'Rest of Hawaii', 'Savannah', 'Singapore', 'Sioux City', 'Tampa Bay', 'Tanunda', 'Trentham East', 'Valdosta', 'Vernonia', 'Victor Harbor', 'Vineland Station', 'Waterloo', 'Weirton', 'Winchester Bay', 'Yorkton', 'Abu Dhabi', 'Dubai', 'Sharjah', 'Agra', 'Ahmedabad', 'Allahabad', 'Amritsar', 'Aurangabad', 'Bangalore', 'Bhopal', 'Bhubaneshwar', 'Chandigarh', 'Chennai', 'Coimbatore', 'Dehradun', 'Faridabad', 'Ghaziabad', 'Goa', 'Gurgaon', 'Guwahati', 'Hyderabad', 'Indore', 'Jaipur', 'Kanpur', 'Kochi', 'Kolkata', 'Lucknow', 'Ludhiana', 'Mangalore', 'Mohali', 'Mumbai', 'Mysore', 'Nagpur', 'Nashik', 'New Delhi', 'Noida', 'Panchkula', 'Patna', 'Puducherry', 'Pune', 'Ranchi', 'Secunderabad', 'Surat', 'Vadodara', 'Varanasi', 'Vizag', 'Bandung', 'Bogor', 'Jakarta', 'Tangerang', 'Auckland', 'Wellington City', 'Birmingham', 'Edinburgh', 'London', 'Manchester', 'Doha', 'Cape Town', 'Inner City', 'Johannesburg', 'Pretoria', 'Randburg', 'Sandton', 'Colombo', 'Ankara', 'Isstanbul']

In [41]:
df["currency"].unique()

<StringArray>
[      'Botswana Pula(P)',     'Brazilian Real(R$)',              'Dollar($)',
     'Emirati Diram(AED)',     'Indian Rupees(Rs.)', 'Indonesian Rupiah(IDR)',
          'NewZealand($)',              'Pounds(£)',        'Qatari Rial(QR)',
                'Rand(R)',  'Sri Lankan Rupee(LKR)',       'Turkish Lira(TL)']
Length: 12, dtype: string

In [37]:
df["city"] = df["city"].replace({
    "Bras�_lia": "Brasília",
    "��stanbul": "Isstanbul"
})

df["currency"] = df["currency"].replace({
    "Pounds(��)": "Pounds(£)"
})

In [46]:
bad_cities = df[df["city"].str.contains("�", na=False)]["city"].unique()

print(bad_cities)

<StringArray>
['S��o Paulo']
Length: 1, dtype: string

In [47]:
df["city"] = df["city"].replace({
    "S��o Paulo": "Sao Paulo"
})

In [48]:
bad_currency = df[df["currency"].str.contains("�", na=False)]["city"].unique()

print(bad_currency)

<StringArray>
[]
Length: 0, dtype: string

In [ ]:
pd.set_option("display.max_columns", None)

In [52]:
df.head()

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,average_cost_for_two,currency,has_table_booking,has_online_delivery,is_delivering_now,switch_to_order_menu,price_range,aggregate_rating,rating_color,rating_text,votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [53]:
df["rating_status"] = np.where(
    df["aggregate_rating"] == 0,
    "Not Rated",
    "Rated"
)

In [54]:
df["rating_clean"] = df["aggregate_rating"].replace(0, np.nan)

In [55]:
print(df[["aggregate_rating", "rating_clean", "rating_status"]].head(10))

   aggregate_rating  rating_clean rating_status
0               4.8           4.8         Rated
1               4.5           4.5         Rated
2               4.4           4.4         Rated
3               4.9           4.9         Rated
4               4.8           4.8         Rated
5               4.4           4.4         Rated
6               4.0           4.0         Rated
7               4.2           4.2         Rated
8               4.9           4.9         Rated
9               4.8           4.8         Rated

In [56]:
df["rating_clean"].mean()

np.float64(3.440024314467108)

In [57]:
binary_cols = [
    "has_table_booking",
    "has_online_delivery",
    "is_delivering_now"
]

for col in binary_cols:
    df[col] = df[col].map({
        "Yes": 1,
        "No": 0
    })

In [59]:
df.head()

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,average_cost_for_two,currency,has_table_booking,has_online_delivery,is_delivering_now,switch_to_order_menu,price_range,aggregate_rating,rating_color,rating_text,votes,rating_status,rating_clean
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),1,0,0,No,3,4.8,Dark Green,Excellent,314,Rated,4.8
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),1,0,0,No,3,4.5,Dark Green,Excellent,591,Rated,4.5
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),1,0,0,No,4,4.4,Green,Very Good,270,Rated,4.4
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),0,0,0,No,4,4.9,Dark Green,Excellent,365,Rated,4.9
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),1,0,0,No,4,4.8,Dark Green,Excellent,229,Rated,4.8

In [60]:
df.drop(columns=["switch_to_order_menu"], inplace=True)

In [62]:
df["log_votes"] = np.log1p(df["votes"])
df["log_votes"]

0       5.752573
1       6.383507
2       5.602119
3       5.902633
4       5.438079
5       5.820083
6       6.255750
7       6.519147
8       6.432940
9       6.278521
10      6.976348
11      6.192362
12      5.686975
13      6.129050
14      5.411646
15      3.401197
16      4.290459
17      5.356586
18      4.779123
19      5.973810
20      6.284134
21      6.428105
22      1.945910
23      2.302585
24      2.484907
25      2.484907
26      2.484907
27      2.397895
28      2.197225
29      1.791759
30      1.098612
31      2.564949
32      2.302585
33      2.302585
34      3.401197
35      2.890372
36      1.791759
37      2.397895
38      1.945910
39      3.433987
40      2.197225
41      2.302585
42      2.079442
43      3.401197
44      3.218876
45      3.401197
46      2.484907
47      2.995732
48      3.713572
49      3.091042
50      3.912023
51      3.091042
52      2.708050
53      1.791759
54      3.258097
55      2.639057
56      2.079442
57      2.197225
58      0.693147
59      3.806662
60      3.218876
61      2.397895
62      3.912023
63      2.890372
64      1.791759
65      2.772589
66      4.094345
67      3.433987
68      1.791759
69      0.000000
70      4.304065
71      2.302585
72      3.688879
73      2.564949
74      4.234107
75      3.850148
76      3.637586
77      1.098612
78      1.098612
79      3.135494
80      4.077537
81      2.484907
82      3.583519
83      3.258097
84      3.555348
85      3.828641
86      3.295837
87      3.610918
88      4.219508
89      4.955827
90      4.997212
91      3.951244
92      4.488636
93      5.036953
94      5.081404
95      4.060443
96      4.077537
97      4.753590
98      3.951244
99      5.525453
100     4.770685
101     3.044522
102     3.258097
103     7.507690
104     6.745236
105     6.822197
106     6.086775
107     5.669881
108     6.326149
109     6.419995
110     5.869297
111     5.961005
112     6.628041
113     6.685861
114     5.860786
115     6.142037
116     6.311735
117     6.298949
118     6.144186
119     6.304449
120     7.002156
121     6.363028
122     5.926926
123     6.576470
124     6.308098
125     6.448889
126     5.921578
127     5.308268
128     5.808142
129     5.720312
130     5.910797
131     6.066108
132     6.073045
133     5.942799
134     6.124683
135     6.473891
136     5.888878
137     5.429346
138     5.673323
139     5.602119
140     5.789960
141     5.762051
142     5.707110
143     3.091042
144     5.472271
145     6.779922
146     6.423247
147     6.779922
148     5.940171
149     5.717028
150     6.289716
151     5.814131
152     6.320768
153     6.714171
154     6.311735
155     6.478510
156     6.018593
157     6.493754
158     5.888878
159     5.831882
160     5.976351
161     6.047372
162     6.077642
163     5.913503
164     6.190315
165     4.595120
166     5.902633
167     5.252273
168     6.063785
169     6.066108
170     5.231109
171     5.398163
172     5.852202
173     5.087596
174     5.081404
175     6.710523
176     6.192362
177     5.537334
178     5.398163
179     6.186209
180     6.061457
181     5.686975
182     5.942799
183     5.560682
184     6.073045
185     5.176150
186     4.574711
187     1.945910
188     3.526361
189     6.194405
190     5.846439
191     5.010635
192     5.802118
193     5.513429
194     4.820282
195     4.700480
196     4.905275
197     6.583409
198     5.365976
199     5.817111
200     5.869297
201     5.141664
202     5.262690
203     5.713733
204     5.874931
205     5.662960
206     5.579730
207     5.463832
208     1.945910
209     3.663562
210     4.812184
211     5.337538
212     4.204693
213     5.521461
214     4.158883
215     4.983607
216     4.430817
217     4.762174
218     4.812184
219     4.962845
220     4.744932
221     5.370638
222     4.762174
223     4.718499
224     3.258097
225     4.859812
226     5.501258
227     4.727388
228     4.976734
229     5.117994
230     5.342334
231     4.919981
232     4.454347
233     4.770685
234     3.988984
235     6.163315
236     4.836282
237     5.308268
238     1.098612
239     1.386294
240     5.123964
241     4.727388
242     5.549076
243     4.820282
244     5.298317
245     5.062595
246     4.615121
247     4.955827
248     5.288267
249     6.933423
250     6.347389
251     6.514713
252     6.208590
253     6.021023
254     4.736198
255     7.012115
256     6.591674
257     6.492240
258     5.916202
259     6.278521
260     6.758095
261     6.850126
262     6.167516
263     5.389072
264     5.370638
265     6.551080
266     5.733341
267     5.062595
268     6.274762
269     3.401197
270     3.526361
271     3.713572
272     5.036953
273     4.189655
274     4.077537
275     4.615121
276     5.056246
277     4.317488
278     4.770685
279     4.430817
280     3.891820
281     5.293305
282     4.844187
283     4.787492
284     4.948760
285     5.075174
286     4.882802
287     4.110874
288     4.499810
289     4.290459
290     4.043051
291     4.430817
292     3.637586
293     3.401197
294     5.480639
295     5.463832
296     4.488636
297     5.347108
298     4.897840
299     5.590987
300     5.147494
301     4.682131
302     5.105945
303     5.209486
304     6.525030
305     5.880533
306     4.499810
307     5.860786
308     5.700444
309     5.768321
310     4.744932
311     4.919981
312     4.691348
313     5.087596
314     5.262690
315     4.543295
316     3.713572
317     4.615121
318     4.584967
319     3.737670
320     6.684612
321     2.944439
322     3.465736
323     4.990433
324     6.171701
325     6.148468
326     5.713733
327     5.669881
328     4.634729
329     5.683580
330     5.278115
331     5.501258
332     5.940171
333     5.411646
334     5.497168
335     4.653960
336     5.036953
337     5.780744
338     5.204007
339     5.758902
340     5.666427
341     5.451038
342     5.752573
343     2.484907
344     2.890372
345     5.176150
346     2.484907
347     4.189655
348     5.267858
349     3.433987
350     6.889591
351     7.049255
352     7.201916
353     6.663133
354     7.165493
355     7.751475
356     6.814543
357     6.787845
358     7.165493
359     6.347389
360     7.430114
361     7.438384
362     7.284821
363     7.133296
364     7.253470
365     6.070738
366     6.343880
367     6.682109
368     7.055313
369     7.600402
370     5.945421
371     2.833213
372     2.995732
373     6.455199
374     7.713785
375     6.675823
376     6.720220
377     5.680173
378     6.220590
379     6.327937
380     7.145984
381     6.507278
382     6.803505
383     6.641182
384     7.147559
385     6.220590
386     6.586172
387     6.173786
388     6.383507
389     7.250636
390     6.809039
391     6.705639
392     6.617403
393     5.863631
394     4.653960
395     4.430817
396     4.521789
397     4.094345
398     5.407172
399     4.804021
400     4.543295
401     4.919981
402     5.081404
403     5.030438
404     4.060443
405     5.257495
406     4.454347
407     4.691348
408     4.890349
409     4.955827
410     5.093750
411     4.976734
412     0.693147
413     5.902633
414     2.302585
415     6.297109
416     6.539586
417     6.639876
418     6.562444
419     6.190315
420     6.545350
421     6.186209
422     6.694562
423     6.584791
424     6.774224
425     6.315358
426     6.963190
427     6.562444
428     7.203406
429     6.401917
430     6.983790
431     5.451038
432     7.308543
433     6.284134
434     6.276643
435     6.543912
436     7.091742
437     6.810142
438     6.781058
439     6.922644
440     6.680855
441     6.617403
442     6.340359
443     6.527958
444     6.538140
445     6.523562
446     5.662960
447     6.688355
448     6.566672
449     6.124683
450     6.533789
451     6.579251
452     7.497762
453     6.326149
454     6.784457
455     5.736572
456     3.555348
457     3.526361
458     3.526361
459     3.555348
460     3.583519
461     3.526361
462     3.401197
463     3.583519
464     3.401197
465     3.433987
466     3.526361
467     3.258097
468     3.433987
469     3.555348
470     3.526361
471     3.496508
472     3.433987
473     3.367296
474     3.583519
475     3.526361
476     4.615121
477     4.532599
478     5.209486
479     4.343805
480     4.867534
481     4.553877
482     4.867534
483     5.187386
484     4.584967
485     5.087596
486     4.812184
487     5.278115
488     4.990433
489     4.770685
490     5.236442
491     5.480639
492     5.717028
493     5.638355
494     5.605802
495     4.077537
496     7.186901
497     7.396335
498     6.826545
499     6.894670
500     6.928538
501     8.057694
502     6.501290
503     5.924256
504     6.915723
505     6.689599
506     7.218177
507     7.261927
508     6.739337
509     7.254178
510     7.093405
511     8.031060
512     7.447751
513     7.533159
514     6.775366
515     7.465655
516     5.828946
517     4.477337
518     4.595120
519     4.430817
520     5.446737
521     5.379897
522     5.225747
523     5.225747
524     5.641907
525     4.927254
526     5.347108
527     5.129899
528     5.497168
529     5.402677
530     3.850148
531     5.572154
532     5.214936
533     5.342334
534     5.505332
535     5.298317
536     5.420535
537     6.356108
538     4.488636
539     4.574711
540     5.323010
541     2.944439
542     4.905275
543     5.252273
544     4.919981
545     4.736198
546     4.248495
547     4.499810
548     4.394449
549     5.170484
550     4.919981
551     4.744932
552     4.543295
553     4.499810
554     4.248495
555     4.465908
556     4.304065
557     4.653960
558     4.624973
559     4.077537
560     5.056246
561     5.056246
562     2.833213
563     3.295837
564     5.337538
565     5.932245
566     6.156979
567     5.416100
568     5.433722
569     4.406719
570     6.047372
571     5.509388
572     5.874931
573     5.594711
574     5.093750
575     5.327876
576     5.627621
577     5.942799
578     5.198497
579     6.265301
580     5.379897
581     5.308268
582     6.077642
583     6.375025
584     6.833032
585     7.278629
586     7.156177
587     5.730100
588     6.813445
589     6.464588
590     5.777652
591     7.828436
592     7.236339
593     6.001415
594     7.209340
595     6.495266
596     5.641907
597     7.210080
598     6.315358
599     6.228511
600     7.793587
601     5.958425
602     6.216606
603     6.300786
604     5.655992
605     5.351858
606     5.921578
607     5.758902
608     4.248495
609     3.526361
610     6.109248
611     6.224558
612     5.262690
613     5.043425
614     4.962845
615     6.098074
616     5.583496
617     5.429346
618     5.880533
619     6.131226
620     5.288267
621     4.969813
622     2.564949
623     3.784190
624     4.948760
625     4.276666
626     4.553877
627     4.477337
628     5.181784
629     3.828641
630     4.897840
631     3.737670
632     4.094345
633     3.850148
634     4.644391
635     4.804021
636     4.262680
637     4.356709
638     4.060443
639     4.595120
640     5.170484
641     4.905275
642     5.117994
643     5.129899
644     7.367077
645     7.182352
646     5.384495
647     6.646391
648     6.595781
649     4.736198
650     6.851185
651     4.158883
652     5.929589
653     5.117994
654     6.548219
655     5.786897
656     6.070738
657     6.613384
658     6.003887
659     5.762051
660     7.037906
661     6.948897
662     5.262690
663     5.117994
664     6.284134
665     4.060443
666     4.343805
667     3.951244
668     4.605170
669     4.430817
670     2.944439
671     4.077537
672     3.988984
673     1.945910
674     3.583519
675     3.496508
676     5.023881
677     3.912023
678     4.672829
679     4.094345
680     4.663439
681     4.663439
682     4.060443
683     4.905275
684     4.077537
685     5.846439
686     5.023881
687     3.970292
688     4.812184
689     4.043051
690     4.521789
691     3.295837
692     4.595120
693     4.718499
694     3.951244
695     5.332719
696     3.806662
697     4.553877
698     6.135565
699     5.624018
700     4.276666
701     4.653960
702     6.778785
703     5.262690
704     4.574711
705     4.948760
706     5.484797
707     4.189655
708     4.158883
709     2.995732
710     3.850148
711     4.330733
712     4.553877
713     3.871201
714     4.276666
715     4.304065
716     3.091042
717     3.850148
718     3.828641
719     3.555348
720     4.499810
721     2.197225
722     3.688879
723     4.317488
724     4.343805
725     4.276666
726     7.790282
727     7.770645
728     9.299724
729     7.211557
730     5.446737
731     8.170186
732     7.254178
733     6.661855
734     5.624018
735     9.176577
736     8.591558
737     6.625392
738     7.161622
739     8.840435
740     6.891626
741     6.442540
742     5.814131
743     8.649274
744     6.006353
745     6.626718
746     3.951244
747     4.158883
748     6.059123
749     4.844187
750     5.411646
751     5.552960
752     4.644391
753     4.779123
754     4.595120
755     3.526361
756     5.170484
757     4.718499
758     3.044522
759     4.644391
760     5.497168
761     5.476464
762     4.859812
763     5.087596
764     4.382027
765     4.795791
766     5.669881
767     5.940171
768     5.043425
769     4.983607
770     5.513429
771     4.983607
772     4.779123
773     5.549076
774     5.159055
775     6.052089
776     5.826000
777     5.433722
778     5.537334
779     4.510860
780     5.288267
781     4.248495
782     5.298317
783     4.043051
784     3.912023
785     5.846439
786     4.499810
787     6.501290
788     6.517671
789     6.878326
790     5.707110
791     6.061457
792     6.930495
793     7.280008
794     5.433722
795     6.890609
796     6.220590
797     6.549651
798     5.986452
799     5.583496
800     5.533389
801     4.465908
802     6.706862
803     5.521461
804     5.877736
805     7.501634
806     6.253829
807     7.316548
808     6.735780
809     7.141245
810     5.257495
811     7.320527
812     6.912743
813     7.507141
814     7.469654
815     7.447168
816     7.183871
817     7.382746
818     6.470800
819     6.610696
820     7.099202
821     8.255569
822     6.756932
823     7.145196
824     7.728856
825     5.313206
826     5.765191
827     4.828314
828     5.616771
829     4.997212
830     5.497168
831     3.218876
832     5.942799
833     5.402677
834     4.454347
835     3.713572
836     4.890349
837     5.318120
838     5.375278
839     5.420535
840     5.703782
841     5.303305
842     5.402677
843     5.087596
844     6.226537
845     4.634729
846     4.753590
847     4.955827
848     5.159055
849     6.008813
850     3.931826
851     4.158883
852     4.595120
853     5.442418
854     4.553877
855     4.174387
856     4.882802
857     4.624973
858     4.804021
859     3.688879
860     4.204693
861     5.170484
862     4.653960
863     4.234107
864     4.499810
865     1.609438
866     2.833213
867     2.197225
868     2.197225
869     2.079442
870     1.609438
871     0.693147
872     1.386294
873     1.386294
874     0.000000
875     1.609438
876     2.079442
877     2.484907
878     0.693147
879     0.000000
880     0.000000
881     3.912023
882     4.077537
883     5.455321
884     6.232448
885     4.595120
886     4.094345
887     0.000000
888     0.693147
889     1.098612
890     4.060443
891     5.703782
892     5.480639
893     2.833213
894     2.833213
895     3.891820
896     3.258097
897     1.386294
898     2.564949
899     1.098612
900     0.000000
901     0.000000
902     0.000000
903     1.098612
904     1.386294
905     0.000000
906     0.000000
907     0.000000
908     0.000000
909     2.772589
910     2.995732
911     2.197225
912     0.000000
913     3.044522
914     2.484907
915     2.484907
916     2.079442
917     2.639057
918     0.000000
919     1.386294
920     0.000000
921     3.258097
922     3.135494
923     3.295837
924     2.833213
925     2.079442
926     3.367296
927     0.000000
928     0.000000
929     0.000000
930     3.465736
931     4.262680
932     4.219508
933     3.583519
934     3.135494
935     2.890372
936     3.688879
937     3.583519
938     3.583519
939     3.496508
940     2.708050
941     2.890372
942     3.583519
943     6.684612
944     4.143135
945     3.218876
946     4.905275
947     3.295837
948     4.543295
949     5.638355
950     4.262680
951     3.465736
952     3.258097
953     2.944439
954     3.332205
955     3.332205
956     3.688879
957     4.844187
958     4.330733
959     4.969813
960     5.036953
961     3.784190
962     1.609438
963     3.258097
964     3.295837
965     1.609438
966     3.135494
967     2.708050
968     2.197225
969     2.197225
970     0.000000
971     0.000000
972     0.000000
973     0.000000
974     1.098612
975     0.000000
976     0.000000
977     0.000000
978     3.044522
979     3.688879
980     4.043051
981     3.784190
982     2.302585
983     3.044522
984     3.737670
985     2.944439
986     4.343805
987     0.693147
988     1.945910
989     5.393628
990     2.484907
991     2.564949
992     2.639057
993     2.079442
994     0.693147
995     0.000000
996     0.693147
997     1.386294
998     0.000000
999     0.693147
1000    1.386294
1001    1.098612
1002    0.000000
1003    0.000000
1004    2.772589
1005    1.791759
1006    0.000000
1007    0.000000
1008    2.302585
1009    1.386294
1010    1.098612
1011    2.079442
1012    2.302585
1013    1.609438
1014    0.693147
1015    0.000000
1016    0.000000
1017    1.098612
1018    0.693147
1019    0.693147
1020    3.367296
1021    3.401197
1022    0.000000
1023    0.693147
1024    0.000000
1025    0.000000
1026    1.945910
1027    2.564949
1028    2.995732
1029    2.708050
1030    2.484907
1031    4.262680
1032    2.944439
1033    2.708050
1034    3.891820
1035    3.970292
1036    0.693147
1037    0.000000
1038    0.000000
1039    1.098612
1040    0.000000
1041    0.000000
1042    0.693147
1043    0.000000
1044    0.000000
1045    0.000000
1046    1.609438
1047    1.386294
1048    0.000000
1049    0.000000
1050    0.693147
1051    0.000000
1052    2.397895
1053    1.791759
1054    1.609438
1055    1.609438
1056    0.000000
1057    0.000000
1058    0.693147
1059    1.386294
1060    1.098612
1061    0.000000
1062    0.000000
1063    3.871201
1064    4.382027
1065    3.401197
1066    0.693147
1067    0.000000
1068    2.890372
1069    2.302585
1070    2.079442
1071    1.791759
1072    2.197225
1073    2.772589
1074    2.833213
1075    1.609438
1076    0.693147
1077    2.397895
1078    2.302585
1079    3.218876
1080    2.995732
1081    2.197225
1082    2.197225
1083    3.688879
1084    2.397895
1085    2.890372
1086    3.637586
1087    3.526361
1088    2.302585
1089    1.386294
1090    1.098612
1091    0.693147
1092    0.000000
1093    0.000000
1094    1.609438
1095    2.708050
1096    2.639057
1097    1.791759
1098    2.564949
1099    2.197225
1100    2.079442
1101    2.944439
1102    3.135494
1103    1.609438
1104    0.000000
1105    0.000000
1106    0.000000
1107    0.000000
1108    1.386294
1109    1.386294
1110    0.000000
1111    1.098612
1112    0.693147
1113    2.397895
1114    2.944439
1115    4.043051
1116    2.708050
1117    1.945910
1118    5.087596
1119    3.970292
1120    0.693147
1121    0.000000
1122    5.220356
1123    3.526361
1124    3.332205
1125    5.793014
1126    4.158883
1127    2.833213
1128    4.532599
1129    4.110874
1130    2.890372
1131    1.945910
1132    2.708050
1133    5.204007
1134    5.017280
1135    2.079442
1136    5.533389
1137    5.236442
1138    5.777652
1139    4.744932
1140    4.394449
1141    5.638355
1142    6.030685
1143    6.472346
1144    7.427739
1145    5.713733
1146    6.815640
1147    7.692570
1148    6.753438
1149    7.017506
1150    7.108244
1151    6.823286
1152    6.400257
1153    6.028279
1154    6.320768
1155    6.248043
1156    6.734592
1157    6.525030
1158    5.583496
1159    5.780744
1160    5.908083
1161    2.833213
1162    4.394449
1163    7.543273
1164    6.688355
1165    1.609438
1166    1.791759
1167    2.397895
1168    1.098612
1169    4.060443
1170    1.609438
1171    1.609438
1172    0.000000
1173    0.000000
1174    1.098612
1175    0.693147

In [ ]:
#easy to create dashboard
price_map = {
    1: "Budget",
    2: "Mid-Range",
    3: "Premium",
    4: "Luxury"
}

df["price_category"] = df["price_range"].map(price_map)

In [64]:
df.head()

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,average_cost_for_two,currency,has_table_booking,has_online_delivery,is_delivering_now,price_range,aggregate_rating,rating_color,rating_text,votes,rating_status,rating_clean,log_votes,price_category
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),1,0,0,3,4.8,Dark Green,Excellent,314,Rated,4.8,5.752573,Premium
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),1,0,0,3,4.5,Dark Green,Excellent,591,Rated,4.5,6.383507,Premium
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),1,0,0,4,4.4,Green,Very Good,270,Rated,4.4,5.602119,Luxury
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),0,0,0,4,4.9,Dark Green,Excellent,365,Rated,4.9,5.902633,Luxury
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),1,0,0,4,4.8,Dark Green,Excellent,229,Rated,4.8,5.438079,Luxury

In [65]:
def rating_category(rating):
    if pd.isna(rating):
        return "Not Rated"
    elif rating < 2.5:
        return "Poor"
    elif rating < 3.5:
        return "Average"
    elif rating < 4.0:
        return "Good"
    elif rating < 4.5:
        return "Very Good"
    else:
        return "Excellent"

df["rating_category"] = df["rating_clean"].apply(rating_category)

In [66]:
df.head()

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,average_cost_for_two,currency,has_table_booking,has_online_delivery,is_delivering_now,price_range,aggregate_rating,rating_color,rating_text,votes,rating_status,rating_clean,log_votes,price_category,rating_category
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),1,0,0,3,4.8,Dark Green,Excellent,314,Rated,4.8,5.752573,Premium,Excellent
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),1,0,0,3,4.5,Dark Green,Excellent,591,Rated,4.5,6.383507,Premium,Excellent
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),1,0,0,4,4.4,Green,Very Good,270,Rated,4.4,5.602119,Luxury,Very Good
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),0,0,0,4,4.9,Dark Green,Excellent,365,Rated,4.9,5.902633,Luxury,Excellent
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),1,0,0,4,4.8,Dark Green,Excellent,229,Rated,4.8,5.438079,Luxury,Excellent

In [67]:
#creating primary cuisines
df["primary_cuisine"] = (
    df["cuisines"]
    .fillna("Unknown")
    .str.split(",")
    .str[0]
    .str.strip()
)

In [68]:

df.head()

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,average_cost_for_two,currency,has_table_booking,has_online_delivery,is_delivering_now,price_range,aggregate_rating,rating_color,rating_text,votes,rating_status,rating_clean,log_votes,price_category,rating_category,primary_cuisine
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),1,0,0,3,4.8,Dark Green,Excellent,314,Rated,4.8,5.752573,Premium,Excellent,French
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),1,0,0,3,4.5,Dark Green,Excellent,591,Rated,4.5,6.383507,Premium,Excellent,Japanese
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),1,0,0,4,4.4,Green,Very Good,270,Rated,4.4,5.602119,Luxury,Very Good,Seafood
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),0,0,0,4,4.9,Dark Green,Excellent,365,Rated,4.9,5.902633,Luxury,Excellent,Japanese
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),1,0,0,4,4.8,Dark Green,Excellent,229,Rated,4.8,5.438079,Luxury,Excellent,Japanese

In [70]:
df.to_csv("zomato_cleaned.csv", index=False)